### ISSUE TITLE
выдает disconnecting client because error error: read econnreset

### ISSUE THREAD

**Issue by nouop226** [YTFort/MIOXY-BOOSTED#4]
я не понимаю что делать чтобы играть с нурика а потом пройти прову если на одном сервере получилось а на фт уже не получается зайти а также выдает вот это
![2024-12-19_17-23-43](https://github.com/user-attachments/assets/6d03f753-83fb-4ca3-9ad9-2aff72eb0b4d)

**Comment by YTFort** [comment]
Здравствуйте, можете более подробно описать проблему?

**Comment by nouop226** [comment]
я пофиксил эту проблему теперь при заходе на сервер с 2 лаунчера просто перестает грузить а там где я с читами кикает за превышено время ожидания получается я делал все по гайду все получилось зашел на серв поиграл вызвали на прову захожу с 2 лаунчера по тому же хосту и просто не грузит  именно не грузится территория а также если и зайдет то вылетит изза прогрузки всего что было на сервере
![Uploading 2024-12-19_20-38-02.png…]()

**Comment by YTFort** [comment]
Это ошибка из за защиты сервера и недоработки программы, ожидайте обновления. Сейчас можете поискать аналоги
